---

- name: Create Jenkins folder on the Host
  file:
    path: "{{ path }}"
    state: directory
    owner: 1000
    group: 1000
    mode: u+rw



    

- name: Start Jenkins-Ansible container
  docker_container:
    name: jen
    image: johnmops/jen-ansible:lts
    state: started
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - /{{ path }}:/var/jenkins_home/
