---

  - name: add nginx ppa
    apt_repository: 
      repo: "ppa:nginx/stable"

  - name: install common packages needed for python application development
    apt: 
      name: "{{ item }}"
    with_items:
      - libpq-dev
      - libmysqlclient-dev
      - libxml2-dev
      - libjpeg62
      - libjpeg62-dev
      - libfreetype6
      - libfreetype6-dev
      - zlib1g-dev
      - mysql-client
      - python-dev
      - python-setuptools
      - python-imaging
      - python-mysqldb
      - python-psycopg2
      - git-core
      - nginx

  - name: install pip
    easy_install: 
      name: pip

  - name: install various libraries with pip
    pip: 
      name: "{{ item }}"
    with_items:
      - virtualenv
      - supervisor
      - uwsgi
