--- 

- name: Increase memory
  raw: sysctl -w vm.max_map_count=262144
  
- name: Move elasticsearch.yml
  template:
    src: templates/elasticsearch.yml
    dest: /opt/elasticsearch/conf/elasticsearch.yml
    owner: root
    group: root

- name: Run Elasticsearch Docker
  docker_container:
    name: elasticsearch
    image: elasticsearch:7.2.0
    state: started
    volumes:
      - /opt/elasticsearch/data:/usr/share/elasticsearch/data/
      - /opt/elasticsearch/conf:/usr/share/elasticsearch/config/
    ports:
     - "9200:9200"
     - "9300:9300"
     
- name: Move Kibana.yml
  template:
    src: templates/kibana.yml
    dest: /opt/kibana/kibana.yml
    owner: root
    group: root

   
     
- name: Run Kibana Docker
  docker_container:
    name: kibana
    image: kibana:7.2.0
    state: started
    volumes:
      - /opt/kibana:/usr/share/kibana/config
    ports:
     - "5601:5601"
     

    
