--- 

- name: Increase memory
  raw: sysctl -w vm.max_map_count=262144
  
- name: Run Elasticsearch Docker
  docker_container:
    name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
    state: started
    ports:
     - "9200:9200"
     - "9300:9300"
     
          
- name: Run Kibana Docker
  docker_container:
    name: kibana
    image: docker.elastic.co/kibana/kibana:7.2.0
    state: started
    links:
      - elasticsearch:elasticsearch
    ports:
     - "5601:5601"
     

    
