---
  
  - name: Install docker
    apt:
      name: docker.io
      state: present
        
  - name: Start docker service
    service:
      name: docker
      state: started

  - name: Create Folder Kibana
    file:
      path: /opt/kibana
      state: directory
      owner: 1000
      group: 1000
      mode: '0777'
      
  - name: Create Folder DB
    file:
      path: opt/elasticsearch/data/
      state: directory
     
  - name: Change Owner
    file:
      path: opt/elasticsearch/data/
      owner: 1000
      group: 1000

 
 
