---

- hosts: all
  gather_facts: False
  remote_user: ubuntu
  become: yes
  become_user: root
  become_method: sudo
  
  tasks:  

    - name: Create Folder for Metricbeat
      file:
        path: /opt/metricbeat/metricbeat-6.5.4-linux-x86_64
        state: directory
        mode: u+rwx
        
    - name: Change Owner
      file:
        path: /opt/metricbeat/metricbeat-6.5.4-linux-x86_64
        recurse: yes
        owner: root
        group: root
        mode: u+rwx
      

    - name: Download Metricbeat
      raw: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-6.5.4-linux-x86_64.tar.gz
  
    - name: Unzip Metricbeat
      raw: tar -C /opt/metricbeat -xzvf metricbeat-6.5.4-linux-x86_64.tar.gz
      
    - name: Template a file to /etc/files.conf
      template:
        src: /templates/metricbeat.yml
        dest: /opt/metricbeat/metricbeat-6.5.4-linux-x86_64/metricbeat.yml
        owner: root
        group: root
        mode: '0777'
   
    - service:
        name: metricbeat
        enabled: yes
        state: started
    
