---

- name: Create Folder for Metricbeat
  file:
    path: /opt/metricbeat
    state: directory
    mode: u+rw

- name: Download Metricbeat
  raw: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-6.5.4-linux-x86_64.tar.gz
  
- name: Unzip Metricbeat
  raw: tar -C /opt/metricbeat xzvf metricbeat-6.5.4-linux-x86_64.tar.gz
  
- name: Rename Metricbeat file
  raw: mv /opt/metricbeat/metricbeat-6.5.4-linux-x86_64 /opt/metricbeat/metricbeat_sys
  
- name: Copy metricbeat-yml
  templates:
    src: /templates/metricbeat.yml
    dest: /opt/metricbeat/metricbeat_sys/metricbeat.yml
    
- name: Start metricbeat
  raw: ./metricbeat -e
    
  
  
